power <- read.table("household_power_consumption.txt", sep=";", header=T, stringsAsFactors=FALSE)
power$Global_active_power <- as.numeric(power$Global_active_power)
power$Global_reactive_power <- as.numeric(power$Global_reactive_power)
power$Voltage <- as.numeric(power$Voltage)
power$Global_intensity <- as.numeric(power$Global_intensity)
power$Sub_metering_1 <- as.numeric(power$Sub_metering_1)
power$Sub_metering_2 <- as.numeric(power$Sub_metering_2)
power$Sub_metering_3 <- as.numeric(power$Sub_metering_3)
power$RealTime <- paste(power$Date, power$Time)
power$RealTime <- strptime(power$RealTime, format='%d/%m/%Y %H:%M:%S')
powersubset <- subset(power, RealTime >= as.POSIXct("2007-02-01 00:00:00") & RealTime <= as.POSIXct("2007-02-03 00:00:00"))
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2), mar = c(4, 4, 2, 1), oma = c(0, 0, 2, 0))
with(powersubset, plot(RealTime, Global_active_power, ylab = "Global Active Power (kilowatts)", xlab="", type="n"))
with(powersubset, lines(RealTime, Global_active_power))

with(powersubset, plot(RealTime, Voltage, ylab = "Voltage", xlab="", type="n"))
with(powersubset, lines(RealTime, Voltage))

with(powersubset, plot(RealTime, Sub_metering_1, ylab = "Energy sub metering", xlab="", type="n", col = c("blue", "red")))
with(powersubset, lines(RealTime, Sub_metering_1, col = "black"))
with(powersubset, lines(RealTime, Sub_metering_2, col = "red"))
with(powersubset, lines(RealTime, Sub_metering_3, col = "blue"))
legend("topright", col = c("black", "blue", "red"), lty=c(1,1,1), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))

with(powersubset, plot(RealTime, Global_reactive_power, ylab = "Global Reactive Power (kilowatts)", xlab="", type="n"))
with(powersubset, lines(RealTime, Global_reactive_power))
dev.off()