power <- read.table("household_power_consumption.txt", sep=";", header=T, stringsAsFactors=FALSE)
power$Global_active_power <- as.numeric(power$Global_active_power)
power$Global_reactive_power <- as.numeric(power$Global_reactive_power)
power$Voltage <- as.numeric(power$Voltage)
power$Global_intensity <- as.numeric(power$Global_intensity)
power$Sub_metering_1 <- as.numeric(power$Sub_metering_1)
power$Sub_metering_2 <- as.numeric(power$Sub_metering_2)
power$Sub_metering_3 <- as.numeric(power$Sub_metering_3)
power$RealTime <- paste(power$Date, power$Time)
power$RealTime <- strptime(power$RealTime, format='%d/%m/%Y %H:%M:%S')
powersubset <- subset(power, RealTime >= as.POSIXct("2007-02-01 00:00:00") & RealTime <= as.POSIXct("2007-02-03 00:00:00"))
png("plot2.png", width=480, height=480)
with(powersubset, plot(RealTime, Global_active_power, ylab = "Global Active Power (kilowatts)", xlab="", type="n"))
with(powersubset, lines(RealTime, Global_active_power))
dev.off()